# 전력 증가 및 키 바운스 설정
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# ZMK Studio (현재 충돌 방지를 위해 꺼둠)
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# 기본 디스플레이 및 커스텀 화면 활성화
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# [핵심] nice!view(ePaper) 모듈 활성화
CONFIG_NICE_EPAPER_ON=y

# 위젯 및 봉고캣 활성화
CONFIG_NICE_OLED_WIDGET_STATUS=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
