# 디바운스 타이밍을 임베디드 표준 규격(5ms)으로 완화하여 CPU 인터럽트 오버헤드 축하
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# 디스플레이 렌더링 작업을 메인 시스템 큐에서 분리하여 전용 스레드에 격리
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# 왼쪽 디스플레이 전용 위젯 설정
CONFIG_NICE_OLED_WIDGET_STATUS=y
CONFIG_NICE_OLED_WIDGET_WPM=y

# 봉고캣 대신 강아지(Luna) 활성화
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
