# ZMK 공식 표준 유저 빌드 워크플로우 규격
name: Build ZMK Firmware
on:
  push:
    paths:
      - 'config/**'
  pull_request:
    paths:
      - 'config/**'
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
